routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/link', 'LinkController');
Route::resource('/redirect', 'RedirectController');

Route::get('/', 'LinkController@create')->name('home');
Route::get('/r/{slug}', 'RedirectController@create')->name('redirect');

Route::get('/redirects', 'RedirectController@index')->name('redirects');
Route::get('/stats', 'RedirectController@stats')->name('stats');

Route::get('/get-data', 'RedirectController@getData');
Route::get('/get-stats', 'RedirectController@getStats');

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Link extends Model
{
    protected $fillable = ['url', 'slug'];

    public function redirects()
    {
        return $this->hasMany(Redirect::class);
    }

    public function setSlugAttribute($value)
    {
        $slug = $value . '-' . Str::random(6);
        $this->attributes['slug'] = Str::slug($slug, '-');
    }
}

app/Redirect.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Redirect extends Model
{
    protected $fillable = ['headers', 'user_agent', 'ip', 'language'];

    public function link()
    {
        return $this->belongsTo(Link::class);
    }

    public function setHeadersAttribute($value)
    {
        unset($value['user-agent']);
        unset($value['cookie']);

        $this->attributes['headers'] = json_encode($value);
    }

    public function setLanguageAttribute($acceptLanguage)
    {
        $this->attributes['language'] = explode(',', $acceptLanguage)[0];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\LinkDisplay;
use App\Link;
use Illuminate\Http\Request;

class LinkController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'url' => 'required|url',
            'slug' => 'required|unique:links'
        ]);

        $link = Link::create($request->all());

        return redirect()->back()->with('message', 'Your short link: ' . LinkDisplay::url($link));
    }
}

app/Http/Controllers/RedirectController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\RedirectData;
use App\Link;
use Illuminate\Http\Request;

class RedirectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response|array
     */
    public function index(Request $request)
    {
        return view('redirects');
    }

    public function getData()
    {
        return RedirectData::getAll()->toArray();
    }

    /**
     * Display a listing of the statistics.
     *
     * @return \Illuminate\Http\Response|array
     */
    public function stats(Request $request)
    {
        return view('stats');
    }

    public function getStats()
    {
        return RedirectData::getStats()->toArray();
    }

    /**
     * Redirect user
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, $slug)
    {
        $link = Link::where('slug', $slug)->firstOrFail();

        $link->redirects()->create([
            'headers' => $request->headers->all(),
            'user_agent' => $request->userAgent(),
            'ip' => $request->getClientIp(),
            'language' => $request->server('HTTP_ACCEPT_LANGUAGE')
        ]);

        return redirect()->to($link->url);
    }
}

resources/views/common/alerts.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <b>Errors:</b>

        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif

resources/views/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="create-page">
        <div class="insert-link">
            @include('common.alerts')

            <div class="jumbotron">
                <div class="col-lg-4 offset-lg-4
                            col-md-6 offset-md-3">
                    <h1 class="text-center">Insert link</h1>

                    <hr class="my-4">

                    <form action="{{ route('link.store') }}" method="post">
                        {{ csrf_field() }}

                        @include('partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <header class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <span class="navbar-brand">SHORT LINK</span>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{ route('home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ route('redirects') }}">Redirects</a>
                    <a class="nav-item nav-link" href="{{ route('stats') }}">Stats</a>
                </div>
            </div>

            <span class="nav-item disabled d-none d-sm-none d-md-none d-lg-block">Service for shortening links</span>
        </nav>
    </header>

    <div class="container">
        @yield('content')
    </div>
</div>
</body>
</html>

resources/views/partials/form.blade.php
<div class="form-group">
    <label for="url">Your URL</label>
    <input type="url" name="url" class="form-control" id="url">
</div>

<div class="form-group">
    <label for="slug">Short name</label>
    <input type="text" name="slug" class="form-control" id="slug">
</div>

<button type="submit" class="btn btn-primary">Submit</button>

resources/views/redirects.blade.php
@extends('layouts.app')

@section('content')
    <div class="data-table">
        <h4>List of redirects</h4>

        <hr>

        <grid-view action="/get-data" :fields="[
            {
                key: 'id',
                label: '№',
                sortable: true,
                thStyle: 'min-width: 50px; width: 50px'
            },
            {
                key: 'link.url',
                label: 'URL',
                sortable: true
            },
            {
                key: 'link.slug',
                label: 'Slug',
                sortable: true
            },
            {
                key: 'language',
                sortable: true
            },
            {
                key: 'ip',
                label: 'IP',
                sortable: true,
            },
            {
                key: 'user_agent',
                sortable: true
            },
            {
                key: 'headers',
                sortable: false,
                formatter: function(value) {
                    let headers = JSON.parse(value);

                    let list = [];
                    Object.entries(headers).map(([key, value]) => {
                        // Add spaces
                        value = value.toString().split(';').join('; ');
                        value = value.toString().split(',').join(', ');

                        // Add header
                        list.push(key + ': ' + value);
                    });

                    return list.join(' | ');
                }
            },
        ]">
        </grid-view>
    </div>
@endsection

resources/views/stats.blade.php
@extends('layouts.app')

@section('content')
    <div class="data-table">
        <h4>Statistics of redirects</h4>

        <hr>

        <grid-view action="/get-stats" :fields="[
            {
                key: 'id',
                label: '№',
                sortable: true,
                thStyle: 'min-width: 50px; width: 50px'
            },
            {
                key: 'link.url',
                label: 'URL',
                sortable: true
            },
            {
                key: 'link.slug',
                label: 'Slug',
                sortable: true
            },
            {
                key: 'redirects_count',
                label: 'Redirects',
                sortable: true
            }
        ]">
        </grid-view>
    </div>
@endsection